"INSERT INTO FOOD (F_NAME, F_PRICE , F_SFNAME) VALUES ('Barbecue',100.00,'barbecue') WHERE NOT EXISTS (SELECT F_NAME FROM FOOD WHERE F_NAME='Barbecue')"
"INSERT INTO FOOD (F_NAME, F_PRICE , F_SFNAME) VALUES ('Margherita',50.00,'margherita') WHERE NOT EXISTS (SELECT F_NAME FROM FOOD WHERE F_NAME='Margherita')"
"INSERT INTO FOOD (F_NAME, F_PRICE , F_SFNAME) VALUES ('Pepperoni',125.00,'pepperoni') WHERE NOT EXISTS (SELECT F_NAME FROM FOOD WHERE F_NAME='Pepperoni')"
"INSERT INTO FOOD (F_NAME, F_PRICE , F_SFNAME) VALUES ('Beef Burger',200.00,'beefBurger') WHERE NOT EXISTS (SELECT F_NAME FROM FOOD WHERE F_NAME='Beef Burger')"
"INSERT INTO FOOD (F_NAME, F_PRICE , F_SFNAME) VALUES ('Rancho Burger',175.00,'ranchoBurger') WHERE NOT EXISTS (SELECT F_NAME FROM FOOD WHERE F_NAME='Rancho Burger')"
"INSERT INTO FOOD (F_NAME, F_PRICE , F_SFNAME) VALUES ('Hamburger Veggie',225.00,'hamburgerVeggie') WHERE NOT EXISTS (SELECT F_NAME FROM FOOD WHERE F_NAME='Hamburger Veggie')"
"INSERT INTO FOOD (F_NAME, F_PRICE , F_SFNAME) VALUES ('Hazelnut Chocolate',40.00,'hazelnutChocolate') WHERE NOT EXISTS (SELECT F_NAME FROM FOOD WHERE F_NAME='Hazelnut Chocolate')"
"INSERT INTO FOOD (F_NAME, F_PRICE , F_SFNAME) VALUES ('Straberry',30.00,'straberry') WHERE NOT EXISTS (SELECT F_NAME FROM FOOD WHERE F_NAME='Straberry')"
"INSERT INTO FOOD (F_NAME, F_PRICE , F_SFNAME) VALUES ('Oreo Choco',45.00,'oreoChoco') WHERE NOT EXISTS (SELECT F_NAME FROM FOOD WHERE F_NAME='Oreo Choco')"


"CREATE TABLE IF NOT EXISTS DELIVERY_PERSON (D_ID INTEGER PRIMARY KEY AUTO_INCREMENT,D_NAME VARCHAR(20),D_PHONE INTEGER,D_RID INTEGER,FOREIGN KEY(`D_ID`) REFERENCES `RESTAURANT` (`R_ID`), D_CID INTEGER ,FOREIGN KEY(`D_ID`) REFERENCES `CUSTOMER_DETAILS`(`C_ID`))"

"INSERT INTO DELIVERY_PERSON (D_NAME,D_PHONE,D_RID,C_ID) VALUES ('SMITH',9876182672)"
"INSERT INTO DELIVERY_PERSON (D_NAME,D_PHONE,D_RID,C_ID) VALUES ('JOHN',8765298728)"
"INSERT INTO DELIVERY_PERSON (D_NAME,D_PHONE,D_RID,C_ID) VALUES ('BILL',6372910737)"
"INSERT INTO DELIVERY_PERSON (D_NAME,D_PHONE,D_RID,C_ID) VALUES ('HAZELWOOD',8900235467)"
"INSERT INTO DELIVERY_PERSON (D_NAME,D_PHONE,D_RID,C_ID) VALUES ('STARC',9637289989)"
"INSERT INTO DELIVERY_PERSON (D_NAME,D_PHONE,D_RID,C_ID) VALUES ('ROOT',7245290981)"
"INSERT INTO DELIVERY_PERSON (D_NAME,D_PHONE,D_RID,C_ID) VALUES ('RUTHERFORD',8654556610)"

"CREATE TABLE IF NOT EXISTS RESTAURANT (R_ID INTEGER PRIMARY KEY AUTO_INCREMENT,R_NAME VARCHAR(20),F_NAME VARCHAR(20),F_PRICE FLOAT(6,2))"

"INSERT INTO RESTAURANT (R_NAME,F_NAME,F_PRICE) VALUES ('Burger Lounge','BEEF BURGER',200.00)"
"INSERT INTO RESTAURANT (R_NAME,F_NAME,F_PRICE) VALUES ('Hot Burger','RANCHO BURGER',175.00)"
"INSERT INTO RESTAURANT (R_NAME,F_NAME,F_PRICE) VALUES ('Burger Bites','HAMBURGER VEGGIE',225.00)"
"INSERT INTO RESTAURANT (R_NAME,F_NAME,F_PRICE) VALUES ('The Old House','BARBECUE',100.00)"
"INSERT INTO RESTAURANT (R_NAME,F_NAME,F_PRICE) VALUES ('Pizza Corner','MARGHERITA',50.00)"
"INSERT INTO RESTAURANT (R_NAME,F_NAME,F_PRICE) VALUES ('Frosting','PEPPERONI',125.00)"
"INSERT INTO RESTAURANT (R_NAME,F_NAME,F_PRICE) VALUES ('Polar Bear','HAZELNUT CHOCOLATE',40.00)"
"INSERT INTO RESTAURANT (R_NAME,F_NAME,F_PRICE) VALUES ('Polar Bear','STRABERRY',30.00)"
"INSERT INTO RESTAURANT (R_NAME,F_NAME,F_PRICE) VALUES ('Polar Bear','OREO CHOCO',45.00)"

